"""phase8_ai_explanation

Revision ID: phase8_ai_explanation
Revises: phase1_tenant
Create Date: 2026-09-07 00:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'phase8_ai_explanation'
down_revision: Union[str, Sequence[str], None] = 'phase1_tenant'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # runs: AI explanation columns (cached per execution, generated by OpenRouter)
    op.add_column(
        'runs',
        sa.Column(
            'ai_explanation',
            sa.Text(),
            nullable=True,
            server_default=sa.text('NULL'),
            comment='Cached LLM-generated explanation of the execution — generated at most once per run',
        ),
    )
    op.add_column(
        'runs',
        sa.Column(
            'ai_explained_at',
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text('NULL'),
            comment='UTC timestamp when ai_explanation was generated',
        ),
    )


def downgrade() -> None:
    op.drop_column('runs', 'ai_explained_at')
    op.drop_column('runs', 'ai_explanation')
